### ISSUE TITLE
mining - ethminer "no gpu device with sufficient memory was found"

### ISSUE THREAD

**Issue by misternils** [ethereum/homestead-guide#105]
Can't get ethminer started with GPU mining. 

Running geth node
loading ethminer -g
gets this error message: "no gpu device with sufficient memory was found. Can't GPU mine. Remove the -G argument"

I have a AMD Firepro w7100. It's a powerful graphics card with lots of memory

**Comment by misternils** [comment]
found that using `--opencl-platform 1` after -G (or instead of?) helps ethminer find find my GPU

**Comment by misternils** [comment]
Well I found a work around, does that really solve the issue?

**Comment by bobsummerwill** [comment]
This is a bug about a specific tool, but this repo is for the Homestead documentation.    We wouldn't fix this issue here.

If you could log a new issue on http://github.com/ethereum/webthree-umbrella so we don't lose track of the detection being unreliable, and/or error message being less than useful, that would be much appreciated!

**Comment by misternils** [comment]
ok, thanks

**Comment by pncookson** [comment]
--opencl-platform 1 before the -G -M worked for me as well.  Thanks for the fix.

**Comment by Darkshadow11353** [comment]
I had the same problem with an rx460 4gb, and using --opencl-platform 1 got it to work, but it says it can't connect to http://127.0.0.1:8545, and keeps retrying. My internet is fine, so I don't think it is the problem

**Comment by Keeganderson** [comment]
I had the same problem a while back and fixed it by adding --opencl-platform 1 but the problem recently came back up. 
I have "ethminer.exe --farm-recheck 200 --opencl-platform 1 -G -S us2.ethermine.org:4444 -FS us1.ethermine.org:4444 -O (address)" but suddenly got the error "no gpu device with sufficient memory was found" again.
Does anyone have another solution?
