### ISSUE TITLE
Fix the Client Implementation Links.

### ISSUE THREAD

**Issue by c0d3inj3cT** [ethereum/homestead-guide#13]
@Souptacular 

Please fix the client implementation links in the documentation here:

https://github.com/ethereum/homestead-guide/blob/master/source/ethereum-ecosystem/client-implementations.rst

The link for the Golang client is incorrect at present. It is pointing to: http://ethereum.github.io/go-ethereum/) instead of http://ethereum.github.io/go-ethereum/

Notice the extra parenthesis at the end? This would lead to a 404 Not Found page. Please update it.

Thanks.

**Comment by Souptacular** [comment]
Thanks! Fixed.
