### ISSUE TITLE
Installing on Ubuntu 14.04 from PPA is missing packages

### ISSUE THREAD

**Issue by zacwitte** [ethereum/homestead-guide#204]
After adding the repositories based on the current [homestead documentation](https://ethereum-homestead.readthedocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/linux-ubuntu-ppa.html) and trying to install `cpp-ethereum` it can't find the packages.

```
$ sudo apt-get install cpp-ethereum
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cpp-ethereum
```

After adding the ethereum-dev PPA it does find the packages, but Ubuntu won't install them.

```
$ sudo apt-get install cpp-ethereum
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cpp-ethereum : Depends: eth but it is not going to be installed
                Depends: ethminer but it is not going to be installed
                Depends: ethkey but it is not going to be installed
                Depends: ethvm but it is not going to be installed
                Depends: alethzero but it is not going to be installed
                Depends: alethone but it is not going to be installed
                Depends: mix but it is not going to be installed
                Depends: solc but it is not going to be installed
                Depends: lllc but it is not going to be installed
                Depends: rlp but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

After manually specifying dependencies it comes down to `libcryptopp-dev` and `libjson-rpc-cpp-dev` that are missing. I've googled but haven't been able to find anything useful about how to install them.

**Comment by Souptacular** [comment]
@bobsummerwill any ideas? I'm not sure about this one.

**Comment by bobsummerwill** [comment]
Oh dear, @zacwitte.    That is annoying.

Which Ubuntu version are you using?   If you look at the [building from source instructions](https://ethereum-homestead.readthedocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html#installing-dependencies-for-ubuntu), you will see that some of the package names changed across versions.   This should already be captured in the per-version PPAs, but maybe we've missing something?   @chriseth.

Earlier versions ...

   sudo apt-get -y install libjson-rpc-cpp-dev

JSON-RPC dev has been renamed in 15.10 ...

    sudo apt-get -y install libjsonrpccpp-dev

Looks like CryptoPP might have changed package name at some stage too?

   libcrypto++-dev

**Comment by bobsummerwill** [comment]
Older Wiki content which might have some clues?

https://github.com/ethereum/webthree-umbrella/wiki/Compatibility-Info-and-Build-Tips
https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Ubuntu

**Comment by mista66** [comment]
add this line to the ethdocs page,  I've opened a pull request for its inclusion https://github.com/ethereum/homestead-guide/pull/311

sudo apt-get install software-properties-common

**Comment by bobsummerwill** [comment]
That PR was merged.   I think we are good :-)

Please comment here again if there are still issues, guys.   Thanks!

**Comment by kusayuzayushko** [comment]
Same issue.

```
The following packages have unmet dependencies:
 cpp-ethereum : Depends: alethzero but it is not going to be installed
                Depends: mix-ide but it is not going to be installed

...

 mix-ide : Depends: libqt5webengine5 but it is not installable
           Depends: qml-module-qtwebengine but it is not installable
...
 alethzero : Depends: libqt5webengine5 but it is not installable
```

**Comment by yisus1977** [comment]
I my case I needed to add universe repository:
sudo add-apt-repository universe
