### ISSUE TITLE
ePub version?

### ISSUE THREAD

**Issue by Talkless** [ethereum/homestead-guide#236]
Hi,

Is it possible to build ePub version for e-reader?

Thanks.

**Comment by Souptacular** [comment]
Yes there is. Visit this page: http://readthedocs.org/projects/ethereum-homestead/downloads/epub/latest/

**Comment by bobsummerwill** [comment]
That's pretty cool, eh, @Souptacular and @zelig, though the formatting is a little weird.
Useful, though!

**Comment by Talkless** [comment]
Wow, thanks @Souptacular !
