### ISSUE TITLE
have improved the Debian 8 manual 

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/homestead-guide#284]
see my

https://gist.github.com/drandreaskrueger/912e704cfc86fd757277a5fd9bd372d4

GUI applications are working. Feel free to add to [Installing dependencies for Debian](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux-debian.html#debian-jessie-8-5).

**Comment by bobsummerwill** [comment]
Great!   Please do feel free to submit a pull-request to that page with any improvements which you think make sense.

CC @programonauta.

**Comment by bobsummerwill** [comment]
Replaced with https://github.com/ethereum/webthree-umbrella/issues/608.
