### ISSUE TITLE
Error on "Installing dependencies for Debian" page

### ISSUE THREAD

**Issue by programonauta** [ethereum/homestead-guide#290]
Found an error on document page [Installing dependencies for Debian](http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux-debian.html#debian-jessie-8-5)

The command `wget -c http://llvm.org/releases/3.7.1/llvm-3.8.0.src.tar.xz` must be updated to `wget -c http://llvm.org/releases/3.8.0/llvm-3.8.0.src.tar.xz`

**Comment by bobsummerwill** [comment]
Fixed - thanks!
