### ISSUE TITLE
Proposal: Add Solium to the list of developer tools

### ISSUE THREAD

**Issue by duaraghav8** [ethereum/homestead-guide#314]
I've been working on a Linter for Solidity for about a month and recently made a stable release.
Its called Solium, it strictly follows the Official Style guide from the Solidity Docs and its usage is similar to that of eslint.
If you'd like to give it a try, you can install it via npm
```
npm install -g solium
```
and visit the [repository](https://github.com/duaraghav8/Solium) for more information.

I'd like to add its name under the Developer tools category. I think it can greatly improve code quality of Dapps. Please let me know if you're interested.

Thanks

**Comment by bobsummerwill** [comment]
Sure - please create a pull request for the changes.
You could also create a PR under the solidity repo, for the http://solidity.readthedocs.org docs.

**Comment by duaraghav8** [comment]
Thanks.
Since I haven't worked with readthedocs before, I had a noob doubt.
**Am I right in saying that I only need to push the changes in the ```rst``` file** (```developer-tools.rst``` in this case)?

I know that we need to ```make html``` to see the final result but since I don't see any compiled HTML on this repo, my assumption is that you have auto-rebuild. So once the change is pushed in an ```rst``` file, it will reflect on the documentation automatically.
