### ISSUE TITLE
I made a community wiki

### ISSUE THREAD

**Issue by jamesray1** [ethereum/homestead-guide#401]
I've made a community wiki about Ethereum. Feel free to have a look at it: https://github.com/jamesray1/Ethereum-introduction/wiki/Ethereum-introduction.

It might be handy to add it here as a Wiki as well.

**Comment by paulvi** [comment]
PPS The whole intro for https://github.com/Ethereum-community is now 

> Deprecated due to being able to make changes within the Ethereum wiki, homestead guide, yellow paper, etc.

So if so,  please close this issue.

**Comment by paulvi** [comment]
post-post-PS

@jamesray1 
Found your work at https://github.com/ethereum/wiki/wiki/Ethereum-introduction

**Comment by jamesray1** [comment]
Yeah I think it's better to wait for Yoichi or other maintainers to review PRs in Ethereum/homestead-guide. Having two split repos isn't advisable when that is being maintained (albeit maybe with nudging).

**Comment by jamesray1** [comment]
And yes https://github.com/ethereum/wiki/wiki/Ethereum-introduction is a more freely editable alternative.

**Comment by jamesray1** [comment]
But I did update the reader.
