### ISSUE TITLE
Ethdocs isn't maintained

### ISSUE THREAD

**Issue by jamesray1** [ethereum/homestead-guide#412]
There are [33 open PRs at the moment](https://web.archive.org/web/20180104002823/https://github.com/ethereum/homestead-guide/pulls), [starting from 21 Jun 2017, not including only one in 2016 that has conflicts](https://web.archive.org/web/20180104011301/https://github.com/ethereum/homestead-guide/pulls?page=2).

**Comment by sneg55** [comment]
I've tried to raise this question, but it seems no one cares about it.

**Comment by jamesray1** [comment]
I've created an unlicense for this repo [here](https://github.com/ethereum/homestead-guide/pull/413), so that the repo can be forked and modified by anyone, e.g. in this repo [here](https://github.com/Ethereum-community/homestead-guide).

**Comment by paulvi** [comment]
@jamesray1 
OK cloning a repository that is not active enough is fine, now at https://github.com/Ethereum-community/homestead-guide

But how about updating https://ethereum-homestead.readthedocs.io/en/latest/ ?

**Comment by jamesray1** [comment]
@paulvi TBH I haven't maintained https://github.com/Ethereum-community/homestead-guide either. I think having a wiki is a better approach. https://github.com/ethereum/wiki/wiki

**Comment by jamesray1** [comment]
Additionally the license for this repo was changed to CC BY-SA-4.0, so anyone should be able to edit it without having copyright issues now. I can add others as a contributor to that repo, however I suggest talking to maintainers here to discuss being added as a contributor to that repo, if interested. You could make a PR to update that page.

**Comment by paulvi** [comment]
Just learned that https://ethereum-homestead.readthedocs.io/en/latest/ = http://ethdocs.org/en/latest/

and while this repository says that 

> Legacy Docs
>    Ethereum Wiki: https://github.com/ethereum/wiki/wiki

That is wiki is legacy, in fact https://github.com/ethereum/wiki/wiki is still being updated.

So the first problem seems what is actually place for documentation?

**Comment by paulvi** [comment]
@jamesray1 Can you rename this issue to "this repository (Ethdocs) isn't maintained"
or even "THIS REPOSITORY (Ethdocs.org) IS NOT MAINTAINED"

**Comment by paulvi** [comment]
referencing @pirapira Yoichi Hirai who could do latest PR merges.

**Comment by jamesray1** [comment]
@paulvi it may be a stretch to say that it is not maintained, maintainers may maintain it, albeit it may require prompting. I'll close this issue.

**Comment by pirapira** [comment]
I've been prompted.  Currently six PRs are open, and I've left a comment on every one of them.

**Comment by jamesray1** [comment]
I would say that https://github.com/ethereum/wiki/wiki is a more appropriate place for documentation. Vitalik Buterin, myself and others edit it. And anyone can freely edit it without having to be added as a collaborator to the repo or require collaborators to review PRs.

Yoichi, sorry to make it look like I was blaming you, note that I did say it it _may_ require prompting. I haven't looked into the context.

**Comment by jamesray1** [comment]
Regarding the legacy doc reference to the wiki I made a PR for that: https://github.com/ethereum/homestead-guide/pull/440.
