### ISSUE TITLE
Homestead RTD UX

### ISSUE THREAD

**Issue by zach-is-my-name** [ethereum/homestead-guide#67]
My experience with the Frontier Guide was very positive and learning Frontier with it was a breeze . 

Why I prefer Gitbook:

- Clean UI (no distractions)
- Side-pane can be hidden (no distractions)
- Side-pane can show full outline, (fly up and down all topics) 

Why I **DO NOT** prefer RTD

- Solid color side-pane is a distraction 
- Inability to hide side-pane
- Inability to expand full outline 

Could someone clarify the reasoning behind using RTD versus Gitbook?

**Comment by zelig** [comment]
*  full outline will be added just required one line change 
* we use RTD cos it has nicer UI and can compile to all imaginable doc formats

I don't like it too much though cos it has extremely counterintuitive and convoluted markup.

Metropolis/Serenity will surely be another system.
