### ISSUE TITLE
I'd Like to Submit My Stackexchange Documentation on Mist Account / Multisig Setup

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/homestead-guide#76]
I'd like to contribute my stackexchange walkthrough on setting up Mist with accounts and a multisig wallet, into the homestead documentation if it meets your guidelines. Here is the post:

http://ethereum.stackexchange.com/questions/1239/what-is-the-recommended-way-to-safely-store-ether/1430#1430

Let me know if you need me to do anything to get this documentation added, if it does meet your guidelines? I can make free time to assist in any way.

**Comment by Souptacular** [comment]
Wonderful! Please submit a PR.

**Comment by taoteh1221** [comment]
Cool, I will get to that this week as soon as I have some free time.

**Comment by taoteh1221** [comment]
Have not forgotten this, just a busy week full of web2 clients loading me up with work...will be free this weekend to do a PR.

**Comment by Souptacular** [comment]
No worries, thanks for the update.

**Comment by taoteh1221** [comment]
I got the text formatting framework and all the required addons installed and working, so I can test whatever I add to the docs in my fork before a PR. Do you have a preferred existing section / page where you'd like me to add my "Setup A Multisig Wallet In Mist" tutorial? I didn't want to just go ahead and choose a category placement / create a category without your input. It seems like it would fit good in a new category / page under "Using Ethereum: The Basics". Maybe "Using Ethereum: The Basics => Setup A Multisig Wallet In Mist" as a new page? Whatever you prefer.

**Comment by bobsummerwill** [comment]
If you are planning on doing anything TODAY, please jump on https://gitter.im/ethereum/homestead-guide to coordinate, @taoteh1221.   It's all a bit of a scramble for Homestead.    If you don't mind waiting until Tuesday, you'll have an easier time of this!

**Comment by taoteh1221** [comment]
@bobsummerwill My time has ended up a bit limited today, didn't realize I had to setup the text formatting framework...that took me an hour to get installed / running smoothly. :smile: Thanks, I'll check in on that gitter channel Tuesday then, and see what you all want to do with this multisig tutorial. Favoriting it now.

**Comment by bobsummerwill** [comment]
Cool - thanks!

**Comment by taoteh1221** [comment]
Your welcome.
